'use strict';

export enum RoleType {
  USER = 'ROLE_USER',
  ADMIN = 'ROLE_ADMIN',
  ANONYMOUS = 'ROLE_ANONYMOUS',
  GUARANTOR = 'ROLE_GUARANTOR',
  CHILD = 'ROLE_CHILD',
  ORGANIZATIONAL = 'ROLE_ORGANIZATIONAL',
  App_MANAGER='ROLE_APP_MANAGER',
  CHILD_GUARDIAN = 'ROLE_CHILD_GUARDIAN',

}
